version: "3"

networks:
  default:
    external:
      name: host

services:
  traefik:
    restart: always
    image: traefik:v2.2.0
    network_mode: host
    read_only: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Traefik/traefik.yaml:/traefik.yaml:ro
      - ./Traefik/etc/traefik:/etc/traefik/
      - ./Traefik/log:/var/log/traefik/
